# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/10 19:46:31 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = memory

SRC = \
	src/ft_bzero.c \
	src/ft_memalloc.c \
	src/ft_memccpy.c \
	src/ft_memcheck.c \
	src/ft_memchr.c \
	src/ft_memcmp.c \
	src/ft_memcpy.c \
	src/ft_memdel.c \
	src/ft_memdup.c \
	src/ft_memmove.c \
	src/ft_memndup.c \
	src/ft_memprint.c \
	src/ft_memset.c

include ../common/compile.mk