# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/17 12:09:20 by pepe              #+#    #+#              #
#    Updated: 2019/08/17 12:14:48 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = structvb

SRC = \
	src/ft_vb_append.c \
	src/ft_vb_elem_free.c \
	src/ft_vb_elem_new.c \
	src/ft_vb_free.c \
	src/ft_vb_new.c \
	src/ft_vb_tobuffer.c

include ../common/compile.mk
