---
sudo: disabled
language: c
os: linux
after_script: make fclean
stage:
- Checks
- Build c90
- Build c99
- Build c11
- Build c18
- Tests
matrix:
    include:
    -   stage: Checks
        script:
        - sudo apt-get install -y python3-yaml
        - python3 .travis_gen.py test.out
        - diff test.out .travis.yml
        - rm -f test.out
        after_script: make fclean
        name: Verify .travis.yml file
    -   stage: Checks
        script:
        - make -C libft
        - find libft -name "*.c" | sed 's/\.c//g' | sed 's/src//g' | sort > c_files
        - find libft -name "*.o" | sed 's/\.o//g' | sed 's/obj//g' | sort > o_files
        - find libft -name "*.d" | sed 's/\.d//g' | sed 's/obj//g' | sort > d_files
        - diff c_files o_files
        - diff c_files d_files
        - wc -l c_files
        - rm -f c_files o_files d_files
        after_script: make fclean
        name: Verify unused file
    -   stage: Checks
        script:
        - grep 'CC =' libft/common/compile.mk | grep gcc
        after_script: make fclean
        name: Verify compiler is gcc
    -   stage: Build c90
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=5 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with gcc 5
    -   stage: Build c90
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=6 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with gcc 6
    -   stage: Build c90
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=7 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with gcc 7
    -   stage: Build c90
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=8 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with gcc 8
    -   stage: Build c90
        script: make -C libft -f test_docker.mk gcc TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with gcc latest
    -   stage: Build c90
        script: make -C libft -f test_docker.mk clang TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c90\""
        after_script: make fclean
        name: Build libft with clang (latest on Debian)
    -   stage: Build c99
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=5 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with gcc 5
    -   stage: Build c99
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=6 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with gcc 6
    -   stage: Build c99
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=7 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with gcc 7
    -   stage: Build c99
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=8 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with gcc 8
    -   stage: Build c99
        script: make -C libft -f test_docker.mk gcc TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with gcc latest
    -   stage: Build c99
        script: make -C libft -f test_docker.mk clang TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c99\""
        after_script: make fclean
        name: Build libft with clang (latest on Debian)
    -   stage: Build c11
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=5 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with gcc 5
    -   stage: Build c11
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=6 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with gcc 6
    -   stage: Build c11
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=7 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with gcc 7
    -   stage: Build c11
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=8 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with gcc 8
    -   stage: Build c11
        script: make -C libft -f test_docker.mk gcc TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with gcc latest
    -   stage: Build c11
        script: make -C libft -f test_docker.mk clang TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c11\""
        after_script: make fclean
        name: Build libft with clang (latest on Debian)
    -   stage: Build c18
        script: make -C libft -f test_docker.mk gcc VERSION_GCC_DOCKER=8 TEST_CMD="make
            ADDITIONAL_FLAGS=\"-std=c18\""
        after_script: make fclean
        name: Build libft with gcc 8
    -   stage: Build c18
        script: make -C libft -f test_docker.mk gcc TEST_CMD="make ADDITIONAL_FLAGS=\"-std=c18\""
        after_script: make fclean
        name: Build libft with gcc latest
    -   stage: Tests
        script: bash tests/test.bash 001_ctype_single
        after_script: make fclean
        name: 001_ctype_single
    -   stage: Tests
        script: bash tests/test.bash 002_math_single
        after_script: make fclean
        name: 002_math_single
    -   stage: Tests
        script: bash tests/test.bash 003_memory_single
        after_script: make fclean
        name: 003_memory_single
    -   stage: Tests
        script: bash tests/test.bash 004_put_single
        after_script: make fclean
        name: 004_put_single
    -   stage: Tests
        script: bash tests/test.bash 005_strstd_single
        after_script: make fclean
        name: 005_strstd_single
    -   stage: Tests
        script: bash tests/test.bash 006_strconv_single
        after_script: make fclean
        name: 006_strconv_single
    -   stage: Tests
        script: bash tests/test.bash 007_strlambda_single
        after_script: make fclean
        name: 007_strlambda_single
    -   stage: Tests
        script: bash tests/test.bash 008_strctype_single
        after_script: make fclean
        name: 008_strctype_single
...
