# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/13 17:50:10 by pepe              #+#    #+#              #
#    Updated: 2019/08/13 18:24:51 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = strctype

SRC = \
	src/ft_stralnum.c \
	src/ft_stralpha.c \
	src/ft_strascii.c \
	src/ft_strblank.c \
	src/ft_strdigit.c \
	src/ft_strlower.c \
	src/ft_strprint.c \
	src/ft_strupper.c \
	src/ft_strxdigit.c

include ../common/compile.mk
