# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/17 12:06:18 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = structsb

SRC = \
	src/ft_sb_append.c \
	src/ft_sb_append_char.c \
	src/ft_sb_free.c \
	src/ft_sb_new.c \
	src/ft_sb_tostring.c

include ../common/compile.mk
