# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/16 00:30:40 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = tabvoid

SRC = \
	src/ft_vtab_append.c \
	src/ft_vtab_delete.c \
	src/ft_vtab_free.c \
	src/ft_vtab_insert.c \
	src/ft_vtab_iter.c \
	src/ft_vtab_len.c \
	src/ft_vtab_new.c \
	src/ft_vtab_pop.c \
	src/ft_vtab_push.c \
	src/ft_vtab_sort.c

include ../common/compile.mk
