# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/17 10:59:23 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = tabstr

SRC = \
	src/from_tabvoid/ft_stab_append.c \
	src/from_tabvoid/ft_stab_delete.c \
	src/from_tabvoid/ft_stab_free.c \
	src/from_tabvoid/ft_stab_insert.c \
	src/from_tabvoid/ft_stab_iter.c \
	src/from_tabvoid/ft_stab_len.c \
	src/from_tabvoid/ft_stab_new.c \
	src/from_tabvoid/ft_stab_pop.c \
	src/from_tabvoid/ft_stab_push.c \
	src/from_tabvoid/ft_stab_sort.c \
	src/ft_stab_join.c \
	src/ft_stab_strparse.c \
	src/ft_stab_strparse_n_free.c \
	src/ft_stab_strsplit.c

include ../common/compile.mk
