# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/09 18:43:59 by pepe              #+#    #+#              #
#    Updated: 2019/08/09 18:45:17 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = ctype

SRC = \
	src/ft_isalnum.c \
	src/ft_isalpha.c \
	src/ft_isascii.c \
	src/ft_isblank.c \
	src/ft_isdigit.c \
	src/ft_islower.c \
	src/ft_isprint.c \
	src/ft_isspace.c \
	src/ft_isupper.c \
	src/ft_iswhitespace.c \
	src/ft_isxdigit.c \
	src/ft_tolower.c \
	src/ft_toupper.c \
	src/ft_toxdigit.c

include ../common/compile.mk
