# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/11 09:50:45 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = put

SRC = \
	src/ft_putchar.c \
	src/ft_putendl.c \
	src/ft_putnbr.c \
	src/ft_putnbrl.c \
	src/ft_putstr.c

include ../common/compile.mk