# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/11 10:40:28 by pepe              #+#    #+#              #
#    Updated: 2019/08/13 17:28:58 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = strconv

SRC = \
	src/num/ft_atoi_base.c \
	src/num/ft_atoi.c \
	src/num/ft_atoll_base.c \
	src/num/ft_atoll.c \
	src/num/ft_convert_base.c \
	src/num/ft_itoa_base.c \
	src/num/ft_itoa.c \
	src/num/ft_lltoa_base.c \
	src/num/ft_lltoa.c \
	src/num/ft_ulltoa_base.c \
	src/num/ft_ulltoa.c \
	src/ft_str_hex_to_array_num.c \
	src/ft_str_to_lower_upper.c

include ../common/compile.mk
