# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/13 17:50:10 by pepe              #+#    #+#              #
#    Updated: 2019/08/13 17:50:28 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = strlambda

SRC = \
	src/ft_strall.c \
	src/ft_strany.c \
	src/ft_striter.c \
	src/ft_striteri.c \
	src/ft_strmap.c \
	src/ft_strmapi.c

include ../common/compile.mk
