# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/09 23:50:38 by pepe              #+#    #+#              #
#    Updated: 2019/08/15 23:44:14 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = math

SRC = \
	src/logarithm/ft_log10.c \
	src/logarithm/ft_logb.c \
	src/logarithm/ft_logui10.c \
	src/logarithm/ft_loguib.c \
	src/logarithm/ft_logul10.c \
	src/logarithm/ft_logulb.c \
	src/logarithm/ft_logull10.c \
	src/logarithm/ft_logullb.c \
	src/pow/ft_curt.c \
	src/pow/ft_nrt.c \
	src/pow/ft_pow.c \
	src/pow/ft_sqrt.c \
	src/trigo/ft_arccos.c \
	src/trigo/ft_arcsin.c \
	src/trigo/ft_arctan.c \
	src/trigo/ft_cos.c \
	src/trigo/ft_sin.c \
	src/trigo/ft_tan.c \
	src/abs/ft_abs.c \
	src/abs/ft_labs.c \
	src/abs/ft_llabs.c \
	src/abs/ft_fabs.c \
	src/abs/ft_dabs.c \
	src/ft_fact.c \
	src/ft_max.c \
	src/ft_min.c \
	src/ft_remquo.c

include ../common/compile.mk
