# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/11 10:31:22 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = strstd

SRC = \
	src/alloc/ft_strdup.c \
	src/alloc/ft_strndup.c \
	src/alloc/ft_strnew.c \
	src/alloc/ft_strsetnew.c \
	src/analyze/cmp/ft_strcmp.c \
	src/analyze/cmp/ft_strequ.c \
	src/analyze/cmp/ft_strncmp.c \
	src/analyze/cmp/ft_strnequ.c \
	src/analyze/ft_strlen.c \
	src/analyze/pos/ft_strcpos.c \
	src/analyze/pos/ft_strcrpos.c \
	src/analyze/pos/ft_strpos.c \
	src/analyze/pos/ft_strrpos.c \
	src/analyze/strstr/ft_strnstr.c \
	src/analyze/strstr/ft_strstr.c \
	src/process/cat/ft_strcat.c \
	src/process/cat/ft_strlcat.c \
	src/process/cat/ft_strncat.c \
	src/process/chr/ft_strchr.c \
	src/process/chr/ft_strrchr.c \
	src/process/cpy/ft_strcpy.c \
	src/process/cpy/ft_strncpy.c \
	src/process/ft_strclr.c \
	src/process/ft_strjoin.c \
	src/process/ft_strrev.c \
	src/process/ft_strsub.c \
	src/process/ft_strtrim.c

include ../common/compile.mk