# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pepe <pepe@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/10 19:45:58 by pepe              #+#    #+#              #
#    Updated: 2019/08/17 11:55:59 by pepe             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOD_NAME = structslist

SRC = \
	src/core/ft_slist_add_cmp.c \
	src/core/ft_slist_add_cpy.c \
	src/core/ft_slist_cpy.c \
	src/core/ft_slist_elem_new.c \
	src/core/ft_slist_free.c \
	src/core/ft_slist_new.c \
	src/modify/ft_slist_addback.c \
	src/modify/ft_slist_addfront.c \
	src/modify/ft_slist_append.c \
	src/modify/ft_slist_append_cp.c \
	src/modify/ft_slist_merge.c \
	src/modify/ft_slist_mergeone.c \
	src/modify/ft_slist_pop.c \
	src/modify/ft_slist_push.c \
	src/modify/ft_slist_push_cp.c \
	src/modify/ft_slist_remove.c \
	src/modify/ft_slist_rev.c \
	src/modify/ft_slist_sort.c \
	src/modify/ft_slist_tovtab.c \
	src/static/ft_slist_get.c \
	src/static/ft_slist_head.c \
	src/static/ft_slist_isempty.c \
	src/static/ft_slist_last.c \
	src/static/ft_slist_size.c \
	src/treat/ft_slist_find.c \
	src/treat/ft_slist_findparam.c \
	src/treat/ft_slist_iter.c \
	src/treat/ft_slist_iteri.c \
	src/treat/ft_slist_iteriparam2.c \
	src/treat/ft_slist_iteriparam.c \
	src/treat/ft_slist_iterparam2.c \
	src/treat/ft_slist_iterparam.c \
	src/treat/ft_slist_map.c

include ../common/compile.mk
